[package]
name = "lean-gym"
version = "0.1"
lean_version = "leanprover-community/lean:3.33.0"
path = "src"

[dependencies]
mathlib = { git = "https://github.com/leanprover-community/mathlib", rev = "2fd713a76e15eebdcdfd2f94472584b3f5f2bfc7" }
minif2f = { git = "https://github.com/openai/miniF2F.git", rev = "2df5c635907a9c293f2f4dc0e9e26956df2d340d" }
