#!/bin/bash
set -euxo pipefail

# NOTE(fzyzcjy) originally `setup_miniF2F.sh`

# run from project root

rm -rf leanpkg.path
rm -rf _target

# cp leanpkg_miniF2F.toml leanpkg.toml # NOTE (fzyzcjy) already copied it to leanpkg.toml
leanpkg configure
bash ./_target/deps/mathlib/scripts/mk_all.sh

{
  printf "/- NOTE THIS FILE IS AUTO GENERATED BY lean-gym/scripts/setup.sh -/\n\n";
  cat ./_target/deps/mathlib/src/all.lean;
  printf "\n\nimport test\nimport valid";
} > ../minif2f/lean/src/all.lean
rm ./_target/deps/mathlib/src/all.lean

leanproject get-mathlib-cache
leanpkg build
